name: CI testing - complete

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

defaults:
  run:
    shell: bash

jobs:
  # ToDo: consider unifying in a single workflow and distributing outputs to all others depending ones
  check-diff:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    timeout-minutes: 5
    # Map a step output to a job output
    outputs:
      focus: ${{ steps.diff-domains.outputs.focus }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get PR diff
      id: diff-domains
      env:
        PR_NUMBER: "${{ github.event.pull_request.number }}"
      run: |
        pip install fire requests
        # python actions/assistant.py list_runtimes $PR_NUMBER
        echo "::set-output name=focus::$(python .github/assistant.py changed_domains $PR_NUMBER 2>&1)"
    - run: echo "${{ steps.diff-domains.outputs.focus }}"

  pytest:
    runs-on: ${{ matrix.os }}
    needs: check-diff
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.6, 3.8, 3.9]
        requires: ['oldest', 'latest']
        exclude:
          - {python-version: 3.6, requires: 'latest'}
          - {python-version: 3.9, requires: 'oldest'}
    env:
      PYTEST_ARTEFACT: test-results-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}.xml
      PYTORCH_URL: https://download.pytorch.org/whl/cpu/torch_stable.html

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    # seems that MacOS jobs take much more than orger OS
    timeout-minutes: 95

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Github Actions: Run step on specific OS: https://stackoverflow.com/a/57948488/4521646
    - name: Setup macOS
      if: runner.os == 'macOS'
      run: |
        python -c "print('PYTEST_TIMEOUT=--timeout=120')" >> $GITHUB_ENV
        brew install gcc libomp ffmpeg # https://github.com/pytorch/pytorch/issues/20030
    - name: Setup Linux
      if: runner.os == 'Linux'
      run: |
        python -c "print('PYTEST_TIMEOUT=--timeout=120')" >> $GITHUB_ENV
        sudo apt update --fix-missing
        sudo apt install -y ffmpeg
    - name: Setup Windows
      if: runner.os == 'windows'
      run: |
        choco install ffmpeg

    - uses: ./.github/actions/caching
      with:
        os: ${{ runner.os }}
        requires: ${{ matrix.requires }}
        python-version: ${{ matrix.python-version }}

    - name: Install base dependencies
      run: |
        pip --version
        pip install --requirement requirements.txt --upgrade --find-links $PYTORCH_URL

    - name: Freeze Numpy (hotfix)
      if: matrix.requires == 'latest'
      run: pip install -q "numpy==1.20.0"  # temp hotfix for cypesq

    - name: Install all dependencies
      run: |
        python ./requirements/adjust-versions.py requirements.txt
        python ./requirements/adjust-versions.py requirements/image.txt
        pip install --requirement requirements/devel.txt --upgrade --find-links $PYTORCH_URL
        pip list

    - name: Tests
      env:
        TEST_DIRS: "${{ needs.check-diff.outputs.focus }}"
      run: |
        phmdoctest README.md --outfile tests/test_readme.py
        python -m pytest torchmetrics $TEST_DIRS --cov=torchmetrics --junitxml="junit/$PYTEST_ARTEFACT" --durations=50 "$PYTEST_TIMEOUT"

    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: $PYTEST_ARTEFACT
        path: "junit/$PYTEST_ARTEFACT"
      if: failure()

    - name: Statistics
      if: success()
      run: |
        coverage xml
        coverage report

    - run: echo "::set-output name=TORCH::$(python -c 'import torch ; print(torch.__version__)' 2>&1)"
      id: info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: cpu,pytest,${{ runner.os }},python${{ matrix.python-version }},torch${{ steps.info.outputs.TORCH }}
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
